repos:
  - repo: https://github.com/psf/black
    rev: 23.7.0  # Use the latest version of Black
    hooks:
      - id: black
  - repo: https://github.com/jendrikseipp/vulture
    rev: 'v2.3'  # or any later Vulture version
    hooks:
      - id: vulture