[tool.vulture]
exclude = ["*.ipynb*.py"]
# ignore_decorators = ["@app.route", "@require_*"]
# ignore_names = ["visit_*", "do_*"]
# make_whitelist = true
min_confidence = 60
# paths = ["myscript.py", "mydir", "whitelist.py"]
# sort_by_size = true
# verbose = true

[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | \.asv
)/
'''